insert
	into
	config.portal_setting (password_reset_days,
	approval_max_level,
	attachment_allowed_file_types,
	attachment_max_file_count,
	attachment_max_file_size,
	currency_format,
	date_format,
	decimal_separator,
	default_currency_id,
	default_customer_home_page,
	default_supplier_home_page,
	is_allow_multiple_user_sessions,
	is_allow_multiple_vendor_sessions,
	is_allow_user_blocking,
	is_ip_address_blocking,
	is_mobile_based_otp_enable,
	is_otp_based_login,
	max_failed_login_attempts,
	number_format,
	password_policy_id,
	portal_home_layout,
	portal_landing_page,
	portal_local_url,
	portal_logo_path1,
	portal_logo_path2,
	portal_name,
	portal_url,
	region_setup_id,
	session_log_out_in_min,
	session_log_out_warning_in_min,
	time_format,
	is_rfq_guest_vendor_allowed,
	is_rfq_item_make_required,
	is_rfq_item_tech_spec_required,
	is_rfq_multiple_contact_persons_allowed,
	pr_schedule_offset_days,
	is_erp_integrated,
	is_pr_cost_center_required,
	is_pr_make_required,
	is_pr_tech_spec_required,
	is_pr_update_after_approval,
	pr_item_remarks_max_length,
	is_disable_tnc_in_po,
	is_disable_tnc_in_rfq,
	is_rfq_item_hsn_required,
	company_quotation_edit_policy_id,
	is_quotation_allow_multiple_quotation,
	is_quotation_allow_negotiation,
	is_quotation_make_required,
	is_item_hsn_required,
	is_item_multi_unit_applicable,
	is_po_capex_indent_validation_applicable,
	is_po_cs_pl_required,
	is_po_hsn_based_tax_selection_enabled,
	is_po_indent_remark_auto_populated,
	is_po_item_make_required,
	is_po_item_tech_spec_required,
	is_po_party_ref_required,
	is_po_payment_terms_applicable,
	is_po_priority_on_po_applicable,
	is_po_route_details_applicable,
	po_cs_fetch_count,
	po_default_due_days,
	rfq_pr_warning_scope_id,
	is_po_cost_center_required,
	country_regulation_id,
	default_country_id,
	is_additional_expense_allowed,
	is_l2_reason_mandatory,
	is_negotiation_allowed,
	is_technical_cs_allowed,
	is_vendor_attachment_required,
	vendor_bank_selection_policy_id,
	vendor_cp_selection_policy_id,
	current_requirement_data_variant_id,
	default_email_signature,
	is_po_auto_publish_enabled,
	default_email_address,
	is_delete_reason_applicable,
	is_rfq_add_vendor_allowed,
	rfq_resend_mail_cooldown_period_in_secs,
	is_po_ack_applicable,
	is_cs_linked_disc_disable,
	is_cs_linked_disc_disable1,
	session_warning_time_in_min,
	is_vendor_profile_editable,
	rate_decimal_precision)
values(
180, 
20, 'pdf', 3, 1048576, '##,##,###.##', 'dd-MM-yyyy', '.', null, 
'/dashboard', '/vendor/dashboard', false, true, true, true, true, true, 5, 
'##,##,##,###', 1, 'reals_layout', 'reals', 'http://192.168.0.1:8080', 
'/assets/images/logo_primary.png', '/assets/images/logo_secondary.png', 'Real Deals', 
'https://realdeals.com', 1, 45, 10, '24h', true, true, true, true, null, false, 
false, false, false, false, 300, false, true, false, 2, true, false, false, false, true,
false, false, false, true, true, true, true, false, true, false, 5, 0, 2, false, 3, 2,
true, true, false, false, true, 2, 2, null, null, false, null, true, true, 60, true, false, 
false, 2, true, 2);
